### ISSUE TITLE
renaming aligned reads

### ISSUE THREAD

**Issue by jharri34** [jharri34/krueger#21]

**Comment by jharri34** [comment]
Currently each sample name is defined by siteName_sampleNumber this will become our universal standard redefining aln[sample_name] ->sample_name

**Comment by jimmyCoder** [comment]
TODO:
Create a script to remove the prefix "aln" from all 72 of our files.

**Comment by jharri34** [comment]
this task was picked up 22 days ago and still not finished im taking over
